import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import importPlugin from 'eslint-plugin-import';

// Flat ESLint config for @eduzone/types. Mirrors the base block of
// apps/admin/eslint.config.mjs — same parser, same @typescript-eslint
// recommended set, same import/order contract (minus the app-specific
// architecture blocks, which only exist inside the app). This package is
// consumed by apps/admin, so its code must satisfy the same lint gate:
// review item 04 removed the "No lint configured yet" echo that let
// violations in packages/* ship through the CI Lint step unnoticed.
export default [
  {
    ignores: ['dist/**', 'node_modules/**'],
  },
  {
    files: ['**/*.{js,mjs,cjs,ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        console: 'readonly',
        process: 'readonly',
        URL: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      import: importPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
      'import/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'newlines-between': 'always',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
    },
  },
  {
    // Generated by `supabase gen types typescript` — the generator emits
    // `{}` for functions/views with no arguments or columns (e.g.
    // `Args: {}`), which no-empty-object-type flags. Hand-editing the
    // generated output would be overwritten on the next regeneration, so
    // the rule is disabled for this file only; every hand-written file
    // keeps the rule at full strictness.
    files: ['src/database.types.ts'],
    rules: {
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },
];
