import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import { Providers } from './providers';

import { routing } from '@/i18n/routing';
import { NONCE_REQUEST_HEADER } from '@/lib/csp-nonce';
import { getDir } from '@/lib/direction';
import '../globals.css';

export const metadata: Metadata = {
  title: 'EduZone Admin Dashboard',
  description: 'Multi-tenant Learning Management Platform — Admin & Management Control Plane',
  keywords: ['EduZone', 'Admin', 'Dashboard', 'LMS', 'Learning Management'],
  icons: { icon: '/icon.svg' },
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!(routing.locales as readonly string[]).includes(locale)) {
    notFound();
  }

  // CSP FIX (2026-09-12): read the per-request nonce generated by
  // middleware and thread it onto <html>. Next.js 15 will then propagate
  // it to every <script> tag it emits (inline runtime chunks, flight
  // payload, etc.), allowing the strict CSP to accept them while still
  // blocking any other inline script injected by an attacker (no nonce).
  const nonce = (await headers()).get(NONCE_REQUEST_HEADER) ?? undefined;

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  const dir = getDir(locale);

  return (
    <html lang={locale} dir={dir} suppressHydrationWarning {...(nonce ? { nonce } : {})}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Cairo:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
